
CREATE DATABASE LAZADA;
USE LAZADA;

CREATE TABLE LOAISANPHAM(
	MALOAISP INT IDENTITY(1,1),
    TENLOAISP NVARCHAR(100),
    MALOAI_CHA INT,
    
    CONSTRAINT LOAISANPHAM_MALOAI PRIMARY KEY (MALOAISP)
);

CREATE TABLE THUONGHIEU(
	MATH INT IDENTITY(1,1),
    TENTH NVARCHAR(100),
    HINHTH TEXT,
    
    CONSTRAINT THUONGHIEU_MATH PRIMARY KEY (MATH)
);

CREATE TABLE SANPHAM(
	MASP INT IDENTITY(1,1),
    TENSP NVARCHAR(200),
    GIA DECIMAL,
    HINHLON TEXT,
    HINHNHO TEXT,
    THONGTIN TEXT,
    SOLUONG INT,
    MALOAISP INT,
    MATH INT,
   
    
    CONSTRAINT SANPHAM_MASP PRIMARY KEY (MASP),
    CONSTRAINT SANPHAM_MALOAISP FOREIGN KEY (MALOAISP) REFERENCES LOAISANPHAM (MALOAISP),
  	CONSTRAINT SANPHAM_MATH FOREIGN KEY (MATH) REFERENCES THUONGHIEU (MATH)
);

CREATE TABLE LOAINHANVIEN(
	MALOAINV INT IDENTITY(1,1),
    TENLOAINV NVARCHAR(20),
    
    CONSTRAINT LOAINHANVIEN_MALOAINV PRIMARY KEY (MALOAINV)
);

CREATE TABLE NHANVIEN(
	MANV INT IDENTITY(1,1),
    TENNV NVARCHAR(100),
    TENDN NVARCHAR(20),
    MATKHAU VARCHAR(20),
    DIACHI TEXT,
    NGAYSINH VARCHAR(10),
    SODT VARCHAR(12),
    GIOITINH BIT,
    CMND	VARCHAR(20),
    MALOAINV INT,
    
    CONSTRAINT NHANVIEN_MANV PRIMARY KEY (MANV),
    CONSTRAINT NHANVIEN_MALOAINV FOREIGN KEY (MALOAINV) REFERENCES LOAINHANVIEN (MALOAINV)
);

CREATE TABLE DONDATHANG(
	MADH	INT IDENTITY(1,1),
    MANV	INT,
    TRANGTHAI	BIT,
    DIACHIGIAO	TEXT,
    NGAYDAT	VARCHAR(10),
    NGAYGIAO	VARCHAR(10),
    MOTA	TEXT,
    
    CONSTRAINT DONDATHANG_MADH PRIMARY KEY (MADH)
);

CREATE TABLE CHITIETDATHANG(
    MADH 	INT,
    MASP	INT,
    SOLUONG	INT,
    
    CONSTRAINT CHITIETDATHANG_MADH_MASP PRIMARY KEY (MADH,MASP),
    CONSTRAINT CHITIETDATHANG_MADH FOREIGN KEY (MADH) REFERENCES DONDATHANG(MADH),
    CONSTRAINT CHITIETDATHANG_MASP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
);

CREATE TABLE LOAIKHUYENMAI(
	MALOAIKM	INT IDENTITY(1,1),
    TENLOAIKM	VARCHAR(200),
    
    CONSTRAINT LOAIKHUYENMAI_MALOAIKM PRIMARY KEY (MALOAIKM)
);

CREATE TABLE CHITIETKHUYENMAI(
    MALOAIKM	INT,
    MASP INT,
    NGAYBATDAUKM VARCHAR(10),
    NGAYKETTHUCKM VARCHAR(10),
    PHANTRAMKM VARCHAR(1),

    CONSTRAINT CHITIETKHUYENMAI_MALOAIKM_MASP PRIMARY KEY (MALOAIKM, MASP),
    CONSTRAINT CHITIETKHUYENMAI_MALOAIKM FOREIGN KEY (MALOAIKM) REFERENCES LOAIKHUYENMAI(MALOAIKM),
     CONSTRAINT CHITIETKHUYENMAI_MASP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
);

CREATE TABLE BINHLUAN(
	MABL INT IDENTITY(1,1),
    MANV INT,
    MASP INT,
    NOIDUNG TEXT,
    NGAYBINHLUAN VARCHAR(10),
     
    CONSTRAINT BINHLUAN_MABL PRIMARY KEY (MABL),
    CONSTRAINT BINHLUAN_MANV FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV),
    CONSTRAINT BINHLUAN_MASP FOREIGN KEY (MASP) REFERENCES SANPHAM (MASP)
);

CREATE TABLE DANHGIA(
    MASP INT,
    MANV INT,
    NOIDUNG TEXT,
    SOSAO VARCHAR(1),
    
    CONSTRAINT DANHGIA_MASP_MANV PRIMARY KEY (MANV, MASP),
    CONSTRAINT DANHGIA_MASP FOREIGN KEY (MASP) REFERENCES SANPHAM (MASP),
    CONSTRAINT DANHGIA_MANV FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV)
);

CREATE TABLE MONGMUON(
	MASP	INT,
    MANV	INT,
    
    CONSTRAINT MONGMUON_MASP_MANV PRIMARY KEY (MASP, MANV),
    CONSTRAINT MONGMUON_MASP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP),
    CONSTRAINT MONGMUON_MANV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);